load(paste0("data/data_total.RData"))
Bezirke_nr <- data_total %>%
  dplyr::select(MapName, Bezirk) %>%
  distinct(Bezirk, .keep_all=TRUE)

load(paste0("data/pop_total.RData")) 

area_data <- readxl::read_excel("data_raw/Area1922.xlsx", sheet="1918") %>%
  filter(!Scale =="Canton") %>%
  select(Year,Canton=CantonShort,MapName, area) %>%
  dplyr::mutate(MapName=recode(MapName,"Aarberg"="Seeland",
                               "Aarwangen" = "Oberaargau",
                               "Aelen" ="Aigle",
                               "Alttoggenburg" = "Toggenburg",
                               "Appenzell Inner-Rhoden" = "Appenzell Innerrhoden",
                               "Aubonne" = "Morges" ,
                               "Avenches" = "Broye-Vully" ,
                               "Balsthal"= "Thal-Gäu",
                               "Bellenz" = "Bellinzona",
                               "Bern" =  "Bern-Mittelland",
                               "Bischofszell" = "Weinfelden",
                               "Bollenz" =  "Blenio",
                               "Boudry" =  "Neuchâtel",
                               "Burgdorf" = "Emmental",
                               "Bürgen" = "Seeland",
                               "Chaux-de-fonds" = "Neuchâtel",
                               "Cossonay" ="Morges",
                               "Courtelary"= "Jura bernois",
                               "Delsberg" = "Delémont",
                               "Diessenhofen"= "Frauenfeld",
                               "Echallens" = "Gros-de-Vaud",
                               "Entremont" = "Entremont",
                               "Ering" = "Hérens",
                               "Erlach" = "Seeland",
                               "Fraubrunnen"	= "Bern-Mittelland",
                               "Freibergen" = "Franches-Montagnes",
                               "Frutigen" = "Frutigen-Niedersimmental",
                               "Gaster" = "See-Gaster",
                               "Glenner"	= "Surselva",
                               "Gossau" = "St. Gallen",
                               "Grandson" = "Jura-Nord vaudois",
                               "Greyerz"	= "Gruyère",
                               "Gundis" = "Conthey",
                               "Heinzenberg" = "Viamala",
                               "Hinterrhein" = "Viamala",
                               "Iferten" = "Jura-Nord vaudois",
                               "Im Boden" = "Imboden",
                               "Inn" = "Engiadina Bassa / Val Müstair",
                               "Payerne" ="Broye-Vully",
                               "Interlaken" = "Interlaken-Oberhasli",
                               "Jouxthal"= "Jura-Nord vaudois",
                               "Konolfingen" = "Bern-Mittelland",
                               "Landbezirk"= "Basel-Stadt",
                               "Lauis"	= "Lugano",
                               "Laupen"= "Bern-Mittelland",
                               "Linkes Ufer" = "Genève",
                               "Genf" = "Genève",
                               "Livinen"= "Leventina",
                               "Locle"= "Neuchâtel",
                               "Luggarus" = "Locarno",
                               "Luzern-Stadt" = "Luzern",
                               "Luzern-Land" = "Luzern",
                               "Mainthal"= "Vallemaggia",
                               "Valle-Maggia"= "Vallemaggia",
                               "Martinach"	= "Martigny",
                               "Mendris"	= "Mendrisio",
                               "Milden"= "Broye-Vully",
                               "Morsee"	="Morges",
                               "Münchweilen" = "Münchwilen",
                               "Münster"	= "Jura bernois",
                               "Münsterthal"	= "Engiadina Bassa / Val Müstair",
                               "Neuenburg" = "Neuchâtel",
                               "Neuenstadt" = "Jura bernois",
                               "Neuss"	= "Nyon",
                               "Neutoggenburg" = "Toggenburg",
                               "Niedau" = "Biel",
                               "Nidau" = "Biel",
                               "Niedersimmentahl" = "Frutigen-Niedersimmental",
                               "Oberhasle"	=  "Interlaken-Oberhasli",
                               "Oberklettgau"= "Kanton Schaffhausen",
                               "Oberlanquart"= "Prättigau / Davos",
                               "Oberrheinthal"	= "Rheintal",
                               "Obersimmentahl" = "Obersimmental-Saanen",
                               "Obertoggenburg"	= "Toggenburg",
                               "Orbe" 	= "Jura-Nord vaudois",
                               "Oron" = "Lavaux-Oron",
                               "Pays-d'Enhaut"	= "Riviera-Pays-d'Enhaut",
                               "Peterlingen" = "Broye-Vully",
                               "Pruntrut" = "Porrentruy",
                               "Rechtes Ufer"	= "Genève",
                               "Revierthal"	= "Riviera",
                               "Reyath"= "Kanton Schaffhausen",
                               "Reiat"= "Kanton Schaffhausen",
                               "Reiath"= "Kanton Schaffhausen",
                               "Rolle"	= "Nyon",
                               "Moësa"	= "Moesa",
                               "Rudolfsthal"= "Neuchâtel",
                               "Ryfthal"	= "Lavaux-Oron",
                               "Saane"	= "Sarine",
                               "Saanen"	= "Obersimmental-Saanen",
                               "Sankt Gallen" = "St. Gallen",
                               "Sankt Moritz"	= "Saint-Maurice",
                               "Sargans" = "Sarganserland",
                               "Schwarzenburg" = "Bern-Mittelland",
                               "Schwiz" = "Schwyz",
                               "See" = "See-Gaster",
                               "Seftigen"	= "Thun",
                               "Siders"	= "Sierre",
                               "Signau"	= "Emmental",
                               "Singine"	= "Sense",
                               "Sitten"	= "Sion",
                               "Stadt Basel"	= "Basel-Stadt",
                               "Stadtbezirk"	= "Genève",
                               "Steckborn" = "Frauenfeld",
                               "Tablat"	= "St. Gallen",
                               "Trachselwald" = "Emmental",
                               "Traversthal"	= "Neuchâtel",
                               "Tscherlitz" =	"Gros-de-Vaud",
                               "Unterklettgau" = "Kanton Schaffhausen",
                               "Unterlanquart" = "Landquart",
                               "Unterrheinthal" = "Rheintal",
                               "Untertoggenburg"	= "Toggenburg",
                               "Unterwalden nid dem Wald" = "Nidwalden",
                               "Unterwalden ob dem Wald"	= "Obwalden",
                               "Ursern"	= "Uri",
                               "Vivis"	= "Riviera-Pays-d'Enhaut",
                               "Vivisbach"	= "Veveyse",
                               "Vorderrhein"	= "Surselva",
                               "Wangen"	= "Oberaargau",
                               "Wifflisburg" = "Broye-Vully",
                               "Wyl" = "Wil",
                               "Schleitheim"	= "Kanton Schaffhausen",
                               "Schaffhausen"	= "Kanton Schaffhausen",
                               "Stein"	= "Kanton Schaffhausen",
                               "Bucheggberg-Kriegstetten" = "Bucheggberg-Wasseramt",
                               "Dorneck-Thierstein" = "Dorneck-Thierstein",
                               "Olten-Gösgen"	= "Olten-Gösgen",
                               "Solothurn-Lebern"	= "Solothurn-Lebern",
                               "Solothurn"	= "Solothurn-Lebern",
                               "Gäu"	= "Thal-Gäu",
                               "Thal"	= "Thal-Gäu",
                               "Bucheggberg"	= "Bucheggberg-Wasseramt",
                               "Dorneck"	= "Dorneck-Thierstein",
                               "Gösgen"	= "Olten-Gösgen",
                               "Wasseramt"	= "Bucheggberg-Wasseramt",
                               "Lebern" = 	"Solothurn-Lebern",
                               "Olten" = "Olten-Gösgen",
                               "Thierstein" = 	"Dorneck-Thierstein",
                               "Büren" = "Seeland",
                               "Davos" = "Prättigau / Davos",
                               "Zürich" = "Bezirk Zürich",
                               "Hinweil" = "Hinwil",
                               "Pfeffikon" =  "Pfäffikon",
                               "Dietikon" = "Bezirk Zürich")) %>%
  group_by(MapName, Year) %>%
  mutate(area_Bezirk = sum(area)) %>%
  ungroup() %>%
  left_join(Bezirke_nr) %>%
  distinct(MapName,Year,.keep_all = TRUE) %>%
  select(-area, -Year)

  
Area <- area_data %>%
  right_join(pop_total) %>%
  mutate(area_Bezirk= area_Bezirk/100,
    densPop=population/area_Bezirk)
  
  # mutate(Inc = Tbc_Bezirk/pop_sum *10000)

write.xlsx(Area ,file=paste0("data/Area.xlsx"),row.names=FALSE, overwrite = TRUE)
# save
save(Area ,file=paste0("data/Area.RData"))