function_population <- function() {

# load population total
load(paste0("data/data_total.RData"))
Bezirke_nr <- data_total %>%
  dplyr::select(MapName, Bezirk) %>%
  distinct(Bezirk, .keep_all=TRUE)

pop_1880_1920 <- readxl::read_excel(paste0("data_raw/",population1860_1920))%>%
  dplyr::select(-`1860`, -`1870`,-`1930`,-`1941`,-`1970`,
         -`1980`,-`1990`,-`2001`,-`2005`,-`2008`) %>%
  gather(., Year, population, `1880`:`1920`, factor_key=TRUE) %>%
  rename(MapName = MapName) %>%
  dplyr::mutate(Bezirk=as.character(Bezirk)) %>%
  dplyr::mutate(Bezirk= recode(Bezirk,
         "2401" = "2400",
         "2402"= "2400",
         "2403"= "2400",
         "2404"= "2400",
         "2405"= "2400",
         "2406"= "2400",
         "201" = "243",
         "202" = "244",
         "203" = "246",
         "204" = "242",
         "205" = "243",
         "206" = "245",
         "207" = "241",
         "208" = "243",
         "209" = "246",
         "210" = "249",
         "211" = "250",
         "212" = "246",
         "213" = "246",
         "214" = "241",
         "215" = "241",
         "216" = "242",
         "217" = "249",
         "218" = "250",
         "219" = "248",
         "220" = "248",
         "221" = "246",
         "222" = "247",
         "223" = "245",
         "224" = "247",
         "225" = "245",
         "226" = "505",
         "301" = "316",
         "302" = "313",
         "304" = "314",
         "305" = "315",
         "111" = "113",
         "112" = "113",
         "1101" = "1116",
         "1102" = "1116",
         "1103" = "1112",
         "1104" = "1113",
         "1105" = "1114",
         "1106" = "1112",
         "1107" = "1115", 
         "1108" = "1114",
         "1109" = "1115",
         "1110" = "1113",
         "1401" = "1400",
         "1402" = "1400",
         "1403" = "1400",
         "1404" = "1400",
         "1405" = "1400",
         "1406" = "1400",
         "1701" = "1721",
         "1702" = "1722",
         "1703" = "1723",
         "1704" = "1723",
         "1705" = "1724",
         "1706" = "1725",
         "1707" = "1726",
         "1708" = "1726",
         "1709" = "1727",
         "1710" = "1727",
         "1711" = "1727",
         "1712" = "1727",
         "1713" = "1728",
         "1714" = "1721",
         "1801" = "1841",
         "1802" = "1842",
         "1803" = "1850",
         "1804" = "1851",
         "1805" = "1851",
         "1806" = "1844",
         "1807" = "1843",
         "1808" = "1846",
         "1809" = "1847",
         "1810" = "1843",
         "1811" = "1849",
         "1812" = "1848",
         "1813" = "1845",
         "1814" = "1850",
         "2001"  = "2011",
         "2002" = "2015",
         "2003" = "2012",
         "2004" = "2012",
         "2005" = "2013",
         "2006" = "2014",
         "2007" = "2012",
         "2008" = "2015",
         "2201" = "2221",
         "2202" = "2227",
         "2203" = "2222",
         "2204" = "2227",
         "2205" = "2223",
         "2206" = "2224",
         "2208" = "2226",
         "2209" = "2227",
         "2210" = "2223",
         "2211" = "2228",
         "2212" = "2224",
         "2213" = "2226",
         "2214" = "2222", 
         "2215" = "2230",
         "2216" = "2228",
         "2217" = "2224",
         "2218" = "2230",
         "2219" = "2224")) %>%
  dplyr::select(-MapName) %>%
  dplyr::group_by(Bezirk,Year) %>%
  dplyr::summarise(population = sum(population)) %>%
  dplyr::ungroup() %>%
  filter(!is.na(population))%>%
  mutate(Year=as.character(Year),
         Year = as.numeric(Year))

pop_extrapolate <- pop_1880_1920 %>%
  mutate(Year = as.character(Year),
         Year = as.numeric(Year)) %>%
  complete(Year = seq(1880,1920, by=1)) %>%
  complete(Year, nesting(Bezirk)) %>%
  group_by(Bezirk) %>%
  arrange(Bezirk, Year) %>%
  mutate(population = round(zoo::na.approx(population, na.rm=FALSE),0))   


# write.xlsx(pop_extrapolate ,file=paste0("data/pop_1880_1920.xlsx"),row.names=FALSE, overwrite = TRUE)


pop_2014_2020 <- readxl::read_excel(paste0("data_raw/",population2014_2020)) %>%
  mutate(MapName=word(MapName ,-1)) %>%
  mutate(MapName=recode(MapName, "d'Aigle"  = "Aigle",
                        "d'Entremont" = "Entremont",
                        "d'Hérens" = "Hérens",
                        "bernois" = "Jura bernois",
                        "Biel/Bienne" = "Biel",
                        "lausannois" = "Lausanne",
                        "Innerrhoden" = "Appenzell Innerrhoden",
                        "Müstair" = "Engiadina Bassa / Val Müstair",
                        "vaudois" = "Jura-Nord vaudois", 
                        "Gallen" = "St. Gallen",
                        "Davos" = "Prättigau / Davos",
                        "Aarberg"="Seeland",
                 "Aarwangen" = "Oberaargau",
                 "Aelen" ="Aigle",
                 "Alttoggenburg" = "Toggenburg",
                 "Appenzell Inner-Rhoden" = "Appenzell Innerrhoden",
                 "Aubonne" = "Morges" ,
                 "Balsthal"= "Solothurn",
                 "Bellenz" = "Bellinzona",
                 "Bern" =  "Bern-Mittelland",
                 "Bischofszell" = "Weinfelden",
                 "Bollenz" =  "Blenio",
                 "Boudry" =  "Neuchâtel",
                 "Burgdorf" = "Emmental",
                 "Bürgen" = "Seeland",
                 "Chaux-de-fonds" = "Neuchâtel",
                 "Cossonay" ="Morges",
                 "Courtelary"= "Jura bernois",
                 "Delsberg" = "Delémont",
                 "Diessenhofen"= "Frauenfeld",
                 "Entremont" = "Entremont",
                 "Ering" = "Hérens",
                 "Erlach" = "Seeland",
                 "Fraubrunnen"	= "Bern-Mittelland",
                 "Freibergen" = "Franches-Montagnes",
                 "Frutigen" = "Frutigen-Niedersimmental",
                 "Gaster" = "See-Gaster",
                 "Glenner"	= "Surselva",
                 "Gossau" = "St. Gallen",
                 "Grandson" = "Jura-Nord vaudois",
                 "Greyerz"	= "Gruyère",
                 "Gundis" = "Conthey",
                 "Heinzenberg" = "Viamala",
                 "Hinterrhein" = "Viamala",
                 "Iferten" = "Jura-Nord vaudois",
                 "Im Boden" = "Imboden",
                 "Inn" = "Engiadina Bassa / Val Müstair",
                 "Interlaken" = "Interlaken-Oberhasli",
                 "Jouxthal"= "Jura-Nord vaudois",
                 "Konolfingen" = "Bern-Mittelland",
                 "Landbezirk"= "Basel-Stadt",
                 "Lauis"	= "Lugano",
                 "Laupen"= "Bern-Mittelland",
                 "Linkes Ufer" = "Genève",
                 "Livinen"= "Leventina",
                 "Locle"= "Neuchâtel",
                 "Luggarus" = "Locarno",
                 "Luzern" = "Luzern",
                 "Luzern-Stadt" = "Luzern",
                 "Luzern-Land" = "Luzern",
                 "Mainthal"= "Vallemaggia",
                 "Martinach"	= "Martigny",
                 "Mendris"	= "Mendrisio",
                 "Milden"= "Broye-Vully",
                 "Morsee"	="Morges",
                 "Münchweilen" = "Münchwilen",
                 "Münster"	= "Jura bernois",
                 "Münsterthal"	= "Engiadina Bassa / Val Müstair",
                 "Neuenburg" = "Neuchâtel",
                 "Neuenstadt" = "Jura bernois",
                 "Neuss"	= "Nyon",
                 "Neutoggenburg" = "Toggenburg",
                 "Niedau" = "Biel",
                 "Niedersimmentahl" = "Frutigen-Niedersimmental",
                 "Oberhasle"	=  "Interlaken-Oberhasli",
                 "Oberklettgau"= "Schaffhausen",
                 "Oberlanquart"= "Prättigau / Davos",
                 "Oberrheinthal"	= "Rheintal",
                 "Obersimmentahl" = "Obersimmental-Saanen",
                 "Obertoggenburg"	= "Toggenburg",
                 "Orbe" 	= "Jura-Nord vaudois",
                 "Oron" = "Lavaux-Oron",
                 "Pays-d'Enhaut"	= "Riviera-Pays-d'Enhaut",
                 "Peterlingen" = "Broye-Vully",
                 "Pruntrut" = "Porrentruy",
                 "Rechtes Ufer"	= "Genève",
                 "Revierthal"	= "Riviera",
                 "Reyath"= "Schaffhausen",
                 "Reiat"= "Schaffhausen",
                 "Rolle"	= "Nyon",
                 "Rudolfsthal"= "Neuchâtel",
                 "Ryfthal"	= "Lavaux-Oron",
                 "Saane"	= "Sarine",
                 "Saanen"	= "Obersimmental-Saanen",
                 "Sankt Gallen" = "St. Gallen",
                 "Sankt Moritz"	= "Maloja",
                 "Sargans" = "Sarganserland",
                 "Schwarzenburg" = "Bern-Mittelland",
                 "Schwiz" = "Schwyz",
                 "See" = "See-Gaster",
                 "Seftigen"	= "Thun",
                 "Siders"	= "Sierre",
                 "Signau"	= "Emmental",
                 "Singine"	= "Sense",
                 "Sitten"	= "Sion",
                 "Stadt Basel"	= "Basel-Stadt",
                 "Stadtbezirk"	= "Genève",
                 "Steckborn" = "Frauenfeld",
                 "Tablat"	= "St. Gallen",
                 "Trachselwald" = "Emmental",
                 "Traversthal"	= "Neuchâtel",
                 "Tscherlitz" =	"Gros-de-Vaud",
                 "Unterklettgau" = "Schaffhausen",
                 "Unterlanquart" = "Landquart",
                 "Unterrheinthal" = "Rheintal",
                 "Untertoggenburg"	= "Toggenburg",
                 "Unterwalden nid dem Wald" = "Nidwalden",
                 "Unterwalden ob dem Wald"	= "Obwalden",
                 "Ursern"	= "Uri",
                 "Vivis"	= "Riviera-Pays-d'Enhaut",
                 "Vivisbach"	= "Veveyse",
                 "Vorderrhein"	= "Surselva",
                 "Wangen"	= "Oberaargau",
                 "Wifflisburg" = "Broye-Vully",
                 "Schleitheim"	= "Kanton Schaffhausen",
                 "Schaffhausen"	= "Kanton Schaffhausen",
                 "Stein"	= "Kanton Schaffhausen",
                 "Bucheggberg-Kriegstetten" = "Bucheggberg-Wasseramt",
                 "Dorneck-Thierstein" = "Dorneck-Thierstein",
                 "Olten-Gösgen"	= "Olten-Gösgen",
                 "Solothurn-Lebern"	= "Solothurn-Lebern",
                 "Solothurn"	= "Solothurn-Lebern",
                 "Gäu"	= "Thal-Gäu",
                 "Thal"	= "Thal-Gäu",
                 "Bucheggberg"	= "Bucheggberg-Wasseramt",
                 "Dorneck"	= "Dorneck-Thierstein",
                 "Gösgen"	= "Olten-Gösgen",
                 "Wasseramt"	= "Bucheggberg-Wasseramt",
                 "Lebern" = 	"Solothurn-Lebern",
                 "Olten" = "Olten-Gösgen",
                 "Thierstein" = 	"Dorneck-Thierstein",
                 "Büren" = "Seeland",
                 "Davos" = "Prättigau / Davos",
                 "Zürich" = "Bezirk Zürich",
                 "Dietikon" = "Bezirk Zürich")) %>%
  left_join(Bezirke_nr) %>%
  dplyr::group_by(Bezirk,Year) %>%
  dplyr::summarise(population = sum(population)) %>%
  dplyr::ungroup() %>%
  filter(!is.na(population)) %>%
  mutate(Year=as.character(Year),
         Year = as.numeric(Year))

# write.xlsx(pop_2014_2020,file=paste0("data/pop_2014_2020.xlsx"),row.names=FALSE, overwrite = TRUE)

pop_total <- rbind(pop_extrapolate, pop_2014_2020)
save(pop_total,file=paste0("data/pop_total.RData"))
write.xlsx(pop_total,file=paste0("data/pop_total.xlsx"),row.names=FALSE, overwrite = TRUE)

}